apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: perfsonar

resources:
- ../../base
- patch-ingress-perfsonar.yaml


# Helm chart definition with values overlay
helmCharts:
- name: perfsonar
  repo: https://gitlab.com/api/v4/projects/62739897/packages/helm/stable
  version: 0.1.0
  namespace: perfsonar
  # base values file
  valuesFile: values.yaml

patches:
  - target:
      version: v1
      kind: Service
      name: perfsonar
    path: patch-svc-perfsonar.yaml